package ru.stqa.pft.addressbook.tests.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {

    app.getNavigationHelper().gotoGroupPage();
    // 9 | click | xpath=//input[@name='selected[]'] | 
    app.getGroupHelper().selectGroup();
    // 10 | click | xpath=//input[@name='delete'] | 
    app.getGroupHelper().deleteGroup();
    // 11 | click | xpath=//a[contains(text(),'group page')] | 
    app.getGroupHelper().returnToGroupPage();

  }

}
