package ru.stqa.pft.addressbook.tests.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.pft.addressbook.tests.model.GroupData;

public class GroupCreationTests extends TestBase {

    @Test
    public void testGroupCreation() {

        app.gotoGroupPage();
        app.initGroupCreation();
        app.fillGroupForm(new GroupData("group 1", "header of group 1", "footer of group 1"));
        app.submitGroupCreation();
        app.returnToGroupPage();

    }


}
