package ru.stqa.pft.addressbook.tests.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {

    app.gotoGroupPage();
    // 9 | click | xpath=//input[@name='selected[]'] | 
    app.selectGroup();
    // 10 | click | xpath=//input[@name='delete'] | 
    app.deleteGroup();
    // 11 | click | xpath=//a[contains(text(),'group page')] | 
    app.returnToGroupPage();

  }

}
