package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupCreationTests extends TestBase {

    @Test
    public void testGroupCreation() {

        gotoGroupPage();
        initGroupCreation();
        fillGroupForm(new GroupData("group 1", "header of group 1", "footer of group 1"));
        submitGroupCreation();
        returnToGroupPage();

    }


}
