package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class GroupCreationTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://127.0.0.1/addressbook/");
    driver.manage().window().setSize(new Dimension(855, 952));
    driver.findElement(By.xpath("//input[@name=\'user\']")).click();
    driver.findElement(By.xpath("//input[@name=\'user\']")).sendKeys("admin");
    driver.findElement(By.xpath("//input[@name=\'user\']")).click();
    driver.findElement(By.xpath("//input[@name=\'pass\']")).sendKeys("secret");
    driver.findElement(By.xpath("//input[@value=\'Login\']")).click();  }

  @Test
  public void testGroupCreation() {

    driver.findElement(By.xpath("//a[contains(text(),\'groups\')]")).click();
    driver.findElement(By.xpath("//input[@name=\'new\']")).click();
    driver.findElement(By.xpath("//input[@name=\'group_name\']")).click();
    driver.findElement(By.xpath("//input[@name=\'group_name\']")).sendKeys("group 1 test");
    driver.findElement(By.xpath("//textarea[@name=\'group_header\']")).click();
    driver.findElement(By.xpath("//textarea[@name=\'group_header\']")).sendKeys("header");
    driver.findElement(By.xpath("//textarea[@name=\'group_footer\']")).click();
    driver.findElement(By.xpath("//textarea[@name=\'group_footer\']")).sendKeys("footer");
    driver.findElement(By.xpath("//input[@name=\'submit\']")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'group page\')]")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'home\')]")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'Logout\')]")).click();
    driver.close();
  }


  @After
  public void tearDown() {
    driver.quit();
  }

  public static boolean isAlertPresent(FirefoxDriver driver) {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

}
